# Generated by Django 3.1 on 2020-08-25 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_timeacessed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeAcessed',
        ),
    ]
